### ISSUE TITLE
Rubyスタイルガイドに沿ってインデントを修正する

### ISSUE THREAD

**Issue by norotime** [yuforest/four_personalities#2]
https://github.com/yuforest/four_personalities/blob/8c5a47d6a29ff071cf5a9b0d37a78744db5750b4/app/controllers/sources_controller.rb#L2

https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md#spaces-indentation

**Comment by yuforest** [comment]
インデントの幅が4つになってしまっていましたね。
修正します。
